# Generated by Django 4.0.4 on 2022-05-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('year', models.CharField(max_length=5)),
                ('rated', models.CharField(max_length=6)),
                ('released', models.CharField(max_length=40)),
                ('runtime', models.CharField(max_length=15)),
                ('genre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=300)),
                ('actors', models.CharField(max_length=400)),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('awards', models.TextField(blank=True, null=True)),
                ('poster', models.ImageField(upload_to='')),
                ('ratings', models.CharField(max_length=200)),
                ('metascore', models.CharField(max_length=255)),
                ('imdbRating', models.CharField(max_length=255)),
                ('imdbVotes', models.CharField(max_length=255)),
                ('imdbID', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=15)),
                ('DVD', models.CharField(max_length=255)),
                ('boxOffice', models.CharField(max_length=255)),
                ('production', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.movie')),
            ],
        ),
    ]
